sudo: required

services:
  - docker

env:
  - PHP_VERSION=7.1
  - PHP_VERSION=7.2
  - PHP_VERSION=7.3

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t cd2team/docker-php:$PHP_VERSION ./ --build-arg PHP_VERSION=$PHP_VERSION

deploy:
  provider: script
  script:
    - docker push cd2team/docker-php:$PHP_VERSION
