sudo: required

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t cd2team/docker-php:7.0 ./7.0/
  - docker build -t cd2team/docker-php:7.1 ./7.1/
  - docker build -t cd2team/docker-php:7.2 ./7.2/

deploy:
  provider: script
  script:
    - docker push cd2team/docker-php:7.0
    - docker push cd2team/docker-php:7.1
    - docker push cd2team/docker-php:7.2
