sudo: required

services:
  - docker

env:
  - PHP_VERSION=5.6
  - PHP_VERSION=7.0
  - PHP_VERSION=7.1
  - PHP_VERSION=7.2

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t cd2team/docker-php:7.0 ./ --build-arg PHP_VERSION=$PHP_VERSION

deploy:
  provider: script
  script:
    - docker push cd2team/docker-php:7.0
